folder_in: /home/vboxuser/tst/file
folder_out: /home/vboxuser/tst/out
folder_ext: /home/vboxuser/tst/ext
folder_badarx: /home/vboxuser/tst/badarx
folder_home: /home/vboxuser/tst/home
count: 10
bs: 5M
format_arch: '*.7z'
